repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff
        name: ruff linting
        args: [--fix]
        types_or: [python, pyi]
      - id: ruff-format
        name: ruff formatting
        types_or: [python, pyi]

  - repo: local
    hooks:
      - id: eslint-gallery-api
        name: eslint gallery api
        entry: cmd /c "cd Lambdas/gallery_api && npm run lint"
        language: system
        files: ^Lambdas/gallery_api/src/
        types: [ts]
        pass_filenames: false

      - id: eslint-frontend
        name: eslint frontend
        entry: cmd /c "cd Frontend && npm run lint"
        language: system
        files: ^Frontend/app/
        types: [ts]
        pass_filenames: false

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.22.1
    hooks:
      - id: gitleaks
        name: gitleaks secret scanning
